general:
  project_name: CRYPPO
  project_full_name: CRYPtocurrency Position Optimization
  version: 0.1.0
  description: "\u0E23\u0E30\u0E1A\u0E1A\u0E08\u0E33\u0E25\u0E2D\u0E07\u0E01\u0E32\
    \u0E23\u0E40\u0E17\u0E23\u0E14\u0E04\u0E23\u0E34\u0E1B\u0E42\u0E15\u0E17\u0E35\
    \u0E48\u0E2A\u0E21\u0E08\u0E23\u0E34\u0E07\u0E2A\u0E33\u0E2B\u0E23\u0E31\u0E1A\
    \u0E01\u0E32\u0E23\u0E1E\u0E31\u0E12\u0E19\u0E32\u0E41\u0E25\u0E30\u0E17\u0E14\
    \u0E2A\u0E2D\u0E1A\u0E2D\u0E31\u0E25\u0E01\u0E2D\u0E23\u0E34\u0E17\u0E36\u0E21\
    \ Reinforcement Learning \u0E02\u0E31\u0E49\u0E19\u0E2A\u0E39\u0E07"
  log_level: INFO
  random_seed: 42
  timezone: Asia/Bangkok
data:
  default_symbol: BTCUSDT
  default_timeframes:
  - 1m
  - 5m
  - 15m
  - 1h
  - 4h
  - 1d
  default_start_date: '2023-01-01'
  default_end_date: '2023-12-31'
  data_dir: data
  raw_dir: data/raw
  processed_dir: data/processed
  indicators_dir: data/indicators
  batch_size: 1024
  window_size: 60
  detail_timeframe: 1m
  base_timeframe: 5m
  file_format: parquet
  use_gpu_for_preprocessing: true
binance:
  base_url: https://api.binance.com/api/v3
  klines_endpoint: /klines
  exchange_info_endpoint: /exchangeInfo
  max_candles_per_request: 1000
  request_delay: 0.5
preprocessing:
  use_log_transform: true
  use_z_score: true
  handle_missing_values: true
  remove_outliers: false
  outlier_std_threshold: 3.0
  fill_missing_strategy: ffill
  make_iid_data: true
  iid:
    method: log_return
    volume_method: pct_change
    other_method: diff
    price_columns:
      - open
      - high
      - low
      - close
    volume_columns:
      - volume
    epsilon: 1.0e-08
    dropna: true
    fillna_value: 0.0
  min_data_points: 1000
  train_test_split_ratio: 0.8
  validation_set_ratio: 0.1
indicators:
  default_indicators:
  - rsi
  - macd
  - bollinger_bands
  - ema
  - sma
  - atr
  - relative_volume
  rsi_period: 14
  macd_fast_period: 12
  macd_slow_period: 26
  macd_signal_period: 9
  bollinger_period: 20
  bollinger_std: 2.0
  ema_periods:
  - 9
  - 21
  - 50
  - 200
  sma_periods:
  - 10
  - 50
  - 200
  atr_period: 14
  relative_volume_period: 10
environment:
  initial_balance: 10000.0
  fee_rate: 0.0025
  leverage: 1.0
  liquidation_threshold: 0.8
  stop_loss: 0.1
  take_profit: 0.2
  action_type: discrete
  slippage: 0.0005
  render_mode: null
  episode_length: null
  reward_function: sharpe
  use_detail_timeframe: true
  use_transaction_costs: true
  use_liquidation: true
  use_realistic_slippage: true
model:
  model_type: double_dqn
  learning_rate: 0.0001
  discount_factor: 0.99
  optimizer: adam
  loss_function: mse
  batch_size: 64
  target_update_frequency: 1000
  replay_buffer_size: 100000
  min_replay_buffer_size: 1000
  exploration_initial: 1.0
  exploration_final: 0.05
  exploration_decay: 0.99
  hidden_layers:
  - 256
  - 128
  - 64
  activation_function: relu
  use_batch_norm: true
  dropout_rate: 0.2
  weight_decay: 1.0e-05
  clip_grad_norm: 1.0
  double_q: true
  dueling: false
  noisy: false
  prioritized_replay: false
  alpha: 0.6
  beta: 0.4
  beta_increment: 0.001
  reg_lambda: 0.01
training:
  total_timesteps: 1000000
  save_frequency: 10000
  eval_frequency: 5000
  log_frequency: 1000
  checkpoint_dir: outputs/models
  log_dir: outputs/logs
  use_tensorboard: true
  max_episode_steps: 1000
  early_stopping_patience: 10
  early_stopping_threshold: 0.01
  num_eval_episodes: 5
backtest:
  start_date: null
  end_date: null
  initial_balance: 10000.0
  fee_rate: 0.0025
  leverage: 1.0
  use_stop_loss: true
  use_take_profit: true
  stop_loss: 0.1
  take_profit: 0.2
  plot_results: true
  save_trades: true
  output_dir: outputs/backtest_results
  verbose: true
cuda:
  use_cuda: true
  device: 0
  precision: float32
  memory_fraction: 0.7
  benchmark: true
  deterministic: false
