binance:
  api_key: YOUR_BINANCE_API_KEY_HERE
  api_secret: YOUR_BINANCE_API_SECRET_HERE
telegram:
  bot_token: YOUR_TELEGRAM_BOT_TOKEN_HERE
  chat_id: YOUR_TELEGRAM_CHAT_ID_HERE
database:
  host: localhost
  port: 5432
  username: postgres
  password: YOUR_DB_PASSWORD_HERE
  database: cryppo
aws:
  access_key_id: YOUR_AWS_ACCESS_KEY_ID_HERE
  secret_access_key: YOUR_AWS_SECRET_ACCESS_KEY_HERE
  region: ap-southeast-1
